# Generated by Django 3.2.7 on 2021-09-24 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='promo_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('field_discount', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stuff_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.category')),
                ('stuff_promo', models.ForeignKey(on_delete=models.SET(''), to='sellerSide.promo')),
            ],
        ),
        migrations.CreateModel(
            name='selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pay_value', models.IntegerField()),
                ('count', models.IntegerField()),
                ('ship_cost', models.IntegerField()),
                ('pay_method', models.CharField(max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('name_stuff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellerSide.stuff')),
            ],
        ),
        migrations.AddField(
            model_name='promo',
            name='promo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.promo_type'),
        ),
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('profit_sell', models.IntegerField()),
                ('sell_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.selling')),
            ],
        ),
    ]
