# Generated by Django 3.2.7 on 2021-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_type',
            field=models.IntegerField(blank=True),
        ),
    ]
