# Generated by Django 3.2.7 on 2021-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0003_alter_promo_promo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stuff',
            name='img_file',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
