# Generated by Django 3.2.4 on 2021-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0008_promo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='quality',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
