# Generated by Django 3.2.4 on 2021-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0009_stuff_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='location',
            field=models.CharField(default='Tulangan', max_length=100),
            preserve_default=False,
        ),
    ]
