# Generated by Django 3.2.4 on 2021-11-14 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerSide', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
