# Generated by Django 3.2.4 on 2021-11-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0013_products_post_ship_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='name_stuff',
        ),
        migrations.AddField(
            model_name='selling',
            name='cart_ordered',
            field=models.ForeignKey(default=1999, on_delete=django.db.models.deletion.DO_NOTHING, to='sellerSide.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selling',
            name='trx_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
