# Generated by Django 3.2.4 on 2021-11-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0014_auto_20211114_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.stuff')),
            ],
        ),
    ]
