# Generated by Django 3.2.5 on 2021-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0016_auto_20211120_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stuff',
            name='barcode',
            field=models.CharField(default=123484623285, max_length=100),
            preserve_default=False,
        ),
    ]
