# Generated by Django 3.2.9 on 2021-12-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0017_auto_20211203_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='barcode',
        ),
    ]
